;;; lab4 Egor Kondratev
;;; 4.35


(defun isNumber (s)
  (and (char>= s #\0) (char<= s #\9))
)

(defun copy-text (text)
  (let (
    (cp-text (make-list (length text) :initial-element (make-string 0)))
    )
    (do ((i 0 (+ i 1)))
      ((>= i (length text)))
      (setf (nth i cp-text) (copy-seq (nth i text)))
    )
    cp-text
  )
)
(defun task (arg-text)
  (let (
    (indplus -1)
    (indstr -1)
    (text (copy-text arg-text))
    )	
  (do ((i 0 (+ i 1)))
    ((>= i (length text)))
    (let ((str (nth i text)))
      (do ((j 0 (+ j 1)))
        ((>= j (length str)))
        (if (char= (char str j) #\+)
          (let ()
            (setq indplus j)
            (setq indstr i)
            (setq j (length str))
            (setq i (length text))
          )
        )
      )
    )
  )
  (if (not (= indplus -1))
    (let ()
    (do ((i 0 (+ i 1)))
      ((>= i indstr))
      (let ((str (nth i text)))
        (do ((j 0 (+ j 1 )))
          ((>= j (length str)))
          (if (isNumber (char str j))
            (setf (char str j) #\-)
          )
        )
      )
    )
    (do ((i 0 (+ i 1)))
      ((>= i indplus))
      (if (isNumber (char (nth indstr text) i))
        (setf (char (nth indstr text) i) #\-)
      )
    )
    )
  )
  text
  )
)


;; (task (list "привет 100 + 12 = 112"))
;; ("привет --- + 12 = 112")
;; (task (list "23 432 текст 03" "еще текст" "цифры 4353 364 и плюс + " "затем еще текст с цифрами 43 и снова плюс +"))
;; (task (list "23423626776" " 45645" "+45645688"))
;; (task (list "Просто" "текст" "без" "плюсов" "но с цифрами" "1 2 3 4 5"))
